_specver: 2

modpack:
  name: Another Quality Modpack 2
  description: Largest Fabric 1.18.1 Modpack with 100+ Unique Biomes | Origins, Tech, Magic, Tiered Gear, New Bosses/Mobs/Mounts

install:
  mcVersion: 1.18.1
  loaderVersion: 0.13.1
  modpackUrl: https://media.forgecdn.net/files/3649/503/AQM2-2.0.4.1.zip
  installerUrl: https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.10.2/fabric-installer-0.10.2.jar
  
  ignoreFiles:
    - mods/optifine*.jar
    - resources/**
    - shaderpacks/**
    - kubejs/assets/**
    - kubejs/client_scripts/**
    - mods/Terralith_v2.0.9_Fabric+Forge.jar
  additionalFiles:
    - url: https://media.forgecdn.net/files/3559/150/krypton-0.1.6.jar
      destination: mods/krypton-0.1.6.jar
    - url: https://media.forgecdn.net/files/3639/128/Mambience-4.0.3%2B1.18.1-noAssets.jar
      destination: mods/Mambience-4.0.2+1.18.1-noAssets.jar
    - url: https://media.forgecdn.net/files/3597/431/jline4mcdsrv-0.3.0.jar
      destination: mods/jline4mcdsrv-0.3.0.jar
  localFiles: ~
  
  installerArguments:
    - "server"
    - "-downloadMinecraft"
    - "-mcversion"
    - "1.18.1"
    - "-loader"
    - "0.12.12"
  modpackFormat: curse
  formatSpecific:
    ignoreProject:
      - 242064 #Item Scroller
      - 250419 #enct descriptions
      - 271492 #IKWID
      - 277668 #Armor Sound Tweak
      - 292908 #illuminations
      - 296468 #NoFog
      - 297038 #CraftPresence
      - 308702 #Mod Menu
      - 317590 #Client MAmbience
      - 325492 #Light Overlay
      - 325625 #Roughly Resources
      - 331965 #enchantment tooltips
      - 334259 #Presence Footsteps
      - 335493 #Dynamic FPS
      - 349630 #WI Zoom
      - 355583 #Advancements Enlarger
      - 365521 #Pling
      - 388252 #Notes
      - 394468 #Sodium
      - 400929 #cAn i MiNe thIS bLOCk?
      - 401648 #Better f3
      - 407206 #Chatheads
      - 401978 #Disable Custom Worlds Advice
      - 407981 #Precise Block Placement
      - 416796 #Fancy Menu
      - 416797 #Konkrete
      - 435044 #better3rdperson
      - 435141 #No Angled brackets
      - 437443 #bettersodiumoptions
      - 447673 #Extra sodium
      - 455508 #Iris
      - 459496 #indium
      - 463169 #Puddles Bugged
      - 495059 #Just ENough Keys
      - 495059 #Just Enough Keys
      - 495267 #Inventory Profiles Next
      - 496150 #Deathlog
      - 502516 #CraftingTweals
      - 511319 #Reeses Sodium Options
      - 515172 #Drippy Loading
      - 530816 #no telemetary
      - 537653 #End Goblin Traders
      - 539382 #Iceberg
      - 541604 #Item borders
      - 542478 #Legendary Tooltips
      - 547692 #Client Tweaks
      - 550387 #otter
  baseInstallPath: ~
  checkFolder: yes
  installLoader: yes
  spongeBootstrapper: ~

launch:
  # specifies the max amount of ram the server is supposed to launch with (Xmx)
  maxRam: 6G
  # specifies the minimal amount of ram the server is supposed to launch with (Xms)
  minRam: 4G
  # specifies whether the server is supposed to auto restart after crash
  autoRestart: yes
  javaArgs:
    - "-server"
    - "-XX:+UseG1GC"
    - "-XX:+ParallelRefProcEnabled"
    - "-XX:MaxGCPauseMillis=100"
    - "-XX:+UnlockExperimentalVMOptions"
    - "-XX:+DisableExplicitGC"
    - "-XX:+AlwaysPreTouch"
    - "-XX:G1NewSizePercent=30"
    - "-XX:G1MaxNewSizePercent=40"
    - "-XX:G1HeapRegionSize=8M"
    - "-XX:G1ReservePercent=20"
    - "-XX:G1HeapWastePercent=5" 
    - "-XX:G1MixedGCCountTarget=4" 
    - "-XX:InitiatingHeapOccupancyPercent=15" 
    - "-XX:G1MixedGCLiveThresholdPercent=90" 
    - "-XX:G1RSetUpdatingPauseTimePercent=5" 
    - "-XX:SurvivorRatio=32" 
    - "-XX:+PerfDisableSharedMem" 
    - "-XX:MaxTenuringThreshold=1" 
    - "-Dusing.aikars.flags=https://mcflags.emc.gs" 
    - "-Daikars.new.flags=true"
    - "-Dlog4j.skipJansi=false"
    
  spongefix: no
  ramDisk: no
  checkOffline: no
  crashLimit: 6
  crashTimer: 60min
  preJavaArgs: ~
  startFile: fabric-server-launch.jar
  forcedJavaPath: ~